In [18]:
!pip install pandas numpy scikit-learn nltk

Requirement already satisfied: pandas in c:\users\vishal\anaconda3\lib\site-packages (2.2.2)
Requirement already satisfied: numpy in c:\users\vishal\anaconda3\lib\site-packages (1.26.4)
Requirement already satisfied: scikit-learn in c:\users\vishal\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: nltk in c:\users\vishal\anaconda3\lib\site-packages (3.9.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\vishal\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\vishal\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\vishal\anaconda3\lib\site-packages (from pandas) (2023.3)
Requirement already satisfied: scipy>=1.6.0 in c:\users\vishal\anaconda3\lib\site-packages (from scikit-learn) (1.15.1)
Requirement already satisfied: joblib>=1.2.0 in c:\users\vishal\anaconda3\lib\site-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\vishal\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: click in c:\users\vishal\anaconda3\lib\site-packages (from nltk) (8.1.7)
Requirement already satisfied: regex>=2021.8.3 in c:\users\vishal\anaconda3\lib\site-packages (from nltk) (2026.2.28)
Requirement already satisfied: tqdm in c:\users\vishal\anaconda3\lib\site-packages (from nltk) (4.66.5)
Requirement already satisfied: six>=1.5 in c:\users\vishal\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: colorama in c:\users\vishal\anaconda3\lib\site-packages (from click->nltk) (0.4.6)

In [22]:
import pandas as pd
import numpy as np
import nltk
import string

from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [24]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Vishal\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [26]:
df = pd.read_csv("imdb_top_1000.csv") 
df.head()

,Poster_Link,Series_Title,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,https://m.media-amazon.com/images/M/MV5BMDFkYT...,The Shawshank Redemption,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,https://m.media-amazon.com/images/M/MV5BM2MyNj...,The Godfather,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,https://m.media-amazon.com/images/M/MV5BMTMxNT...,The Dark Knight,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,https://m.media-amazon.com/images/M/MV5BMWMwMG...,The Godfather: Part II,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,https://m.media-amazon.com/images/M/MV5BMWU4N2...,12 Angry Men,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [28]:
print(df.columns)

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

In [30]:
print(df.columns)
df['genre'] = df['Genre']

Index(['Poster_Link', 'Series_Title', 'Released_Year', 'Certificate',
       'Runtime', 'Genre', 'IMDB_Rating', 'Overview', 'Meta_score', 'Director',
       'Star1', 'Star2', 'Star3', 'Star4', 'No_of_Votes', 'Gross'],
      dtype='object')

In [32]:
df = df[['Overview', 'Genre']].copy()
df.dropna(inplace=True)
df.head()

                                            Overview                 Genre
0  Two imprisoned men bond over a number of years...                 Drama
1  An organized crime dynasty's aging patriarch t...          Crime, Drama
2  When the menace known as the Joker wreaks havo...  Action, Crime, Drama
3  The early life and career of Vito Corleone in ...          Crime, Drama
4  A jury holdout attempts to prevent a miscarria...          Crime, Drama

In [8]:
df['Genre'] = df['Genre'].apply(lambda x: x.split(',')[0])

In [38]:
df['clean_plot'] = df['Overview']
df.head()

,Overview,Genre,clean_plot
0,Two imprisoned men bond over a number of years...,Drama,Two imprisoned men bond over a number of years...
1,An organized crime dynasty's aging patriarch t...,"Crime, Drama",An organized crime dynasty's aging patriarch t...
2,When the menace known as the Joker wreaks havo...,"Action, Crime, Drama",When the menace known as the Joker wreaks havo...
3,The early life and career of Vito Corleone in ...,"Crime, Drama",The early life and career of Vito Corleone in ...
4,A jury holdout attempts to prevent a miscarria...,"Crime, Drama",A jury holdout attempts to prevent a miscarria...

In [40]:
tfidf = TfidfVectorizer(max_features=10000, ngram_range=(1,2))
X = tfidf.fit_transform(df['clean_plot']).toarray()

y = df['Genre']

In [42]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [44]:
model = LogisticRegression(max_iter=2000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=2000)

In [46]:
y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

Accuracy: 0.075

In [48]:
print(confusion_matrix(y_test, y_pred))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

In [54]:
def predict_genre(text):
    vector = tfidf.transform([text]).toarray()
    return model.predict(vector)[0]

In [56]:
print("Genre Name:")
print(predict_genre("A police man fights thief"))

Genre Name:
Drama